### ISSUE TITLE
product.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [contentand/shop#2]
Я бы реализовал этот компонент чисто презентационным. Если надо добавить товар в корзину, тогда он генерит родительскому компоненту аутпут. Это позволит не внедрять в него сервисы и родительский компонент будет ответственным за то, чтобы получить товары и чтобы добавить в корзину.

**Comment by contentand** [comment]
Да, хорошее замечание.

**Comment by contentand** [comment]
Done
