### ISSUE TITLE
product-list.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [contentand/shop#4]
private products: Product[];
Думаю, что это свойство должно быть публичным, раз оно используется в темплейте.

**Comment by contentand** [comment]
Да, интересный поинт.
Даже с приватным полем тесплейт может его видеть.
Видимо из-за того, что после компиляции TS приватность пропадает, как я прочитал в ответе на вопрос:
https://stackoverflow.com/questions/37506343/private-and-public-in-angular-2-component/37506946

Видимо, модификатор доступа в данном случае лишний.

**Comment by VZhyrytskiy** [comment]
Если билдить для продакшина, то там будет проверка, чтобы приватные поля не были доступны в темплейте. Будет ошибка, если использовать приватное поле в темпейте. Для дев режима ошибки нет. Но лучше так не делать.

**Comment by contentand** [comment]
Спасибо. Действительно, я билдил лишь в дев моде.
